Replaced aiohttp with requests
As using async aiohttps causes this exception quite often:
async with session.get(url) as resp:
AttributeError: '_RequestContextManager' object has no attribute '_resp'